// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolucaoSimpar2.Models;

#nullable disable

namespace SolucaoSimpar2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220624172744_Inicial-criacao")]
    partial class Inicialcriacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SolucaoSimpar2.Models.Caminhao", b =>
                {
                    b.Property<int>("CaminhaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaminhaoId"), 1L, 1);

                    b.Property<string>("Eixo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_eixo");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_placa");

                    b.HasKey("CaminhaoId");

                    b.ToTable("tb_caminhao");
                });

            modelBuilder.Entity("SolucaoSimpar2.Models.Motorista", b =>
                {
                    b.Property<int>("MotoristaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotoristaId"), 1L, 1);

                    b.Property<int>("CaminhaoId")
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_nome");

                    b.Property<string>("UltimoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_sobrenome");

                    b.HasKey("MotoristaId");

                    b.HasIndex("CaminhaoId");

                    b.ToTable("tb_motorista");
                });

            modelBuilder.Entity("SolucaoSimpar2.Models.Viagem", b =>
                {
                    b.Property<int>("ViagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViagemId"), 1L, 1);

                    b.Property<string>("DataViagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dt_viagem");

                    b.Property<string>("KmTotal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_km_total");

                    b.Property<string>("LocalEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_local_entrega");

                    b.Property<string>("LocalSaida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_local_saida");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("int");

                    b.HasKey("ViagemId");

                    b.HasIndex("MotoristaId");

                    b.ToTable("tb_viagem");
                });

            modelBuilder.Entity("SolucaoSimpar2.Models.Motorista", b =>
                {
                    b.HasOne("SolucaoSimpar2.Models.Caminhao", "Caminhao")
                        .WithMany("Motoristas")
                        .HasForeignKey("CaminhaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caminhao");
                });

            modelBuilder.Entity("SolucaoSimpar2.Models.Viagem", b =>
                {
                    b.HasOne("SolucaoSimpar2.Models.Motorista", "Motorista")
                        .WithMany("Viagens")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("SolucaoSimpar2.Models.Caminhao", b =>
                {
                    b.Navigation("Motoristas");
                });

            modelBuilder.Entity("SolucaoSimpar2.Models.Motorista", b =>
                {
                    b.Navigation("Viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
